version: "3.3"  # optional since v1.27.0
services:
  flask:
    build: .
    #command: flask run --host=0.0.0.0
    command: gunicorn -b 0.0.0.0:5000 app:app --reload
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - PYTHONUNVUFFERED=True
    ports: 
      - "5000:5000"
    volumes:
      - ./:/root